# Generated by Django 4.1 on 2023-09-14 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_band_active_band_biography_band_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="description",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="type",
            field=models.CharField(
                choices=[
                    ("vêtements", "Clothing"),
                    ("affiches", "Posters"),
                    ("divers", "Miscellaneous"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="year",
            field=models.IntegerField(
                default=2020,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2024),
                ],
            ),
            preserve_default=False,
        ),
    ]
